version: "3"

networks:
  djamoedje:
    driver: bridge

volumes:
  mysql:

services:
  nginx_be:
    image: nginx:alpine
    container_name: nginx_djamoedje_be
    restart: unless-stopped
    tty: true
    ports:
      - "8000:80"
    volumes:
      - ./BE-sales:/var/www/app
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - mysql
    networks:
      - djamoedje

  mysql:
    platform: linux/amd64
    image: mysql
    container_name: mysql_djamoedje
    restart: unless-stopped
    tty: true
    ports:
      - "${MYSQL_HOST_PORT}:${MYSQL_DOCKER_CONTAINER_PORT}"
    volumes:
      - mysql:/var/lib/mysql
    environment:
      MYSQL_DATABASE: djamoedje
      MYSQL_USER: ${MYSQL_DB_USER}
      MYSQL_PASSWORD: ${MYSQL_DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_DB_ROOT_PASSWORD}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    networks:
      - djamoedje

  phpmyadmin:
    image: phpmyadmin
    restart: unless-stopped
    container_name: phpmyadmin_djamoedje
    ports:
      - "8888:80"
    environment:
      - PMA_ARBITRARY=1
    networks:
      - djamoedje

  php:
    build:
      context: ./BE-sales
      dockerfile: Dockerfile
    container_name: be_djamoedje
    restart: unless-stopped
    tty: true
    working_dir: /var/www/app
    volumes:
      - ./BE-sales:/var/www/app
    networks:
      - djamoedje

  vue:
    build:
      context: ./FE-sales
      dockerfile: Dockerfile
    container_name: fe_djamoedje
    restart: unless-stopped
    tty: true
    working_dir: /var/www/app
    volumes:
      - ./FE-sales:/var/www/app
    ports:
      - "${VUE_HOST_PORT}:${VUE_DOCKER_CONTAINER_PORT}"
    networks:
      - djamoedje